//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FindTools.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FINDTOOLS_DIALOG            102
#define IDS_STRING_FILENAME             102
#define IDS_STRING_CHINESELINE          103
#define IDS_STRING_CODEPREVIEW          104
#define IDS_STRING_FONT                 105
#define IDS_STRING_STOPCLEW             106
#define IDS_STRING_CLEW                 107
#define IDS_STRING_SELECTFOLD           108
#define IDS_STRING_DSELECTFOLD          109
#define IDS_STRING_STOP                 110
#define IDS_STRING_SCANRESULT           111
#define IDS_STRING_SCANING              112
#define IDS_STRING_RESULT               113
#define CG_IDR_POPUP_MACRO_TOOL         114
#define IDS_STRING_CHECKCLEW            114
#define IDS_STRING_BEGIN                115
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_FINDCHINESE          129
#define IDD_DIALOG_FINDSTRING           130
#define IDD_DIALOG_MACROTOOL            131
#define IDB_BITMAP_DELETE               132
#define IDB_BITMAP_SINGLEOUT            133
#define IDD_DIALOG_HELP                 134
#define IDD_DIALOG_FINDCHINESEEX        142
#define IDD_DIALOG_FINDCHINESE_FUNC     143
#define IDD_DIALOG_FINDCHINESE_FILE     144
#define IDD_DIALOG_FINDCHINESE_FOLD     145
#define FINDTOOLS_ICON                  148
#define IDB_BITMAP_DEL                  149
#define IDB_BITMAP_NEW                  150
#define IDB_BITMAP_TD2                  153
#define IDB_BITMAP_TD4                  154
#define IDB_BITMAP_TD1                  155
#define IDB_BITMAP_TD5                  156
#define IDB_BITMAP_TD3                  157
#define IDC_BUTTON_SELECTFOLD           1000
#define IDC_CHECK_SUBFOLD               1001
#define IDC_BUTTON_SETFONT              1003
#define IDC_LIST_FILELIST               1004
#define IDC_STATIC_RESULT               1005
#define IDC_STATIC_CLEW                 1006
#define IDC_RICHEDIT_PREVIEW            1007
#define IDC_PROGRESS_FINDCHINESE        1008
#define IDC_EDIT_PREFIX                 1010
#define IDC_STATIC_USEDTIMER            1011
#define IDC_EDIT_MACRO                  1015
#define IDC_BUTTON_SELECTFILE           1016
#define IDC_LIST_MACRO_LISTFILE         1018
#define IDC_BUTTON_SINGLE               1021
#define IDC_BUTTON_ALL                  1022
#define IDC_BUTTON_UP                   1023
#define IDC_BUTTON_DOWN                 1024
#define IDC_PROGRESS_MACRO              1025
#define IDC_STATIC_EMAIL                1028
#define IDC_STATIC_HELP                 1030
#define IDC_CHECK_FAST                  1032
#define IDC_EDIT_STRING                 1033
#define IDC_EDIT_FILES                  1034
#define IDC_CHECK_FRONT                 1035
#define IDC_BUTTON_EXCEPTION            1044
#define IDC_STATIC_SEARCHFOLD           1047
#define IDC_COMBO_SELECTFOLD            1048
#define IDC_BUTTON_SCANING              1049
#define IDC_EDIT_FINDCHINESEFUNC        1050
#define IDC_LIST_FINDCHINESEFUNC        1051
#define IDC_BUTTON_FINDCHINESEFUNC_ADD  1052
#define IDC_BUTTON_FINDCHINESEFUNC_DEL  1053
#define IDC_LIST_FINDCHINESEEXT_FILE    1054
#define IDC_LIST_FINDCHINESE_FOLD       1055
#define IDC_BUTTON_TUDING               1060
#define IDC_CHECK_TUDING                1062
#define ID_MENU_SINGLEOUT               32771
#define ID_MENU_DELETE                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
